host: mongodb # Hostname of mongodb
port: 27017 # Port of mongodb
login:  server # Login of mongodb
password:  fi5t5mgk5gio54vkor4 # Password of mongodb
database: Game # Database name
users:
  collection: users # Collection name for users
games:
  collection: games # Collection name for games
